/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GlobalSearch200Response { 
    recipes?: Array<any>;
    ingredients?: Array<any>;
    metadata?: Array<any>;
}

