/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Returns searchresult of instructions belonging to the queried recipe
 */
export interface InstructionSearch { 
    /**
     * ID of the recipe
     */
    recipe_id?: string;
    /**
     * Array with ID\'s of instructions
     */
    instruction_ids?: Array<string>;
}

