/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response on a metadata search request
 */
export interface MetadataSearchResponse { 
    /**
     * UUID of the recipe
     */
    recipe_id?: string;
    /**
     * Array with category UUIDs belonging to the recipe
     */
    category_ids?: Array<string>;
    /**
     * Array with tag UUIDs belonging to the recipe
     */
    tag_ids?: Array<string>;
    /**
     * UUID of the difficulty level associated to a recipe
     */
    difficulty_level_id?: string;
    /**
     * UUID of the preparation time associated to a recipe
     */
    preparation_time_id?: string;
    /**
     * UUID of the cuisine type associated to a recipe
     */
    cuisine_type_id?: string;
}

