/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model to send to the metadata search endpoint. All fields are optional, but at least one is required
 */
export interface MetadataSearchRequest { 
    /**
     * ID of a recipe to base the search on
     */
    recipe_id?: string;
    /**
     * ID of a category to base the search on
     */
    category_id?: string;
    /**
     * ID of a tag to base the search on
     */
    tag_id?: string;
    /**
     * ID of a difficulty level to base the search on
     */
    difficulty_level_id?: string;
    /**
     * ID of a cuisine type to base the search on
     */
    cuisine_type_id?: string;
    /**
     * minimum preparation time in minutes 
     */
    min_prep_time?: number;
    /**
     * maximum preparation time in minutes
     */
    max_prep_time?: number;
}

